name: Continuous Integration - Reusable
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      #      - run: echo OK
      #        name: code Build
      - run: echo OK
        name: code Lint
      - run: npm install
        name: Install Nodejs modules
      - run: echo npm run test:unit
        name: code Unit Test
      - run: echo npm run test:integration
        name: code integration Test
      - run: echo /opt/sonar-scanner-6.1.0.4477-linux-x64/bin/sonar-scanner -Dsonar.host.url=http://sonarqube-internal.shujathdevops.online:9000 -Dsonar.projectKey=${{ inputs.project-name }}  -Dsonar.qualitygate.wait=true - ${{ secrets.vault_token}}
        name: Code Review
      - run: echo software Release
        name: Software Release





